// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pwxjcewhqjixncvfnifr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3eGpjZXdocWppeG5jdmZuaWZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNDc3NjQsImV4cCI6MjA2NTkyMzc2NH0.Rm4yv0fZSpUjt3gyVaowClOz98TYUTs7PF8YtorLaKw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
  // --- START: Connection Stability Fix ---
  // The realtime object is configured to make the WebSocket connection more resilient.
  // This is crucial for long-running applications, as it helps prevent the connection
  // used by `onAuthStateChange` from becoming stale or dropping unexpectedly.
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
  },
  // --- END: Connection Stability Fix ---
  global: {
    headers: {
      'X-Client-Info': 'supabase-js-web'
    }
  }
});